Peek-Pick/peek-pick-backend

src/main/java/org/beep/sbpp/config/QuerydslConfig.java
src/main/java/org/beep/sbpp/points/entities/PointEntity.java
src/main/java/org/beep/sbpp/points/entities/PointLogsEntity.java
src/main/java/org/beep/sbpp/points/entities/PointStoreEntity.java
src/test/java/org/beep/sbpp/points/PointsRepoTests.java
src/test/java/org/beep/sbpp/points/PointsServiceTests.java

[🧪test(points)] PR test

---

src/main/java/org/beep/sbpp/users/entities/BaseEntity.java
src/main/java/org/beep/sbpp/users/entities/UserEntity.java

[🧪test] users PR test

---

src/main/java/org/beep/sbpp/admin/notice/controller/NoticeController.java
src/main/java/org/beep/sbpp/admin/notice/domain/Notice.java
src/main/java/org/beep/sbpp/admin/notice/domain/NoticeImage.java
src/main/java/org/beep/sbpp/admin/notice/dto/NoticeRequestDto.java
src/main/java/org/beep/sbpp/admin/notice/dto/NoticeResponseDto.java
src/main/java/org/beep/sbpp/admin/notice/exception/ErrorResponse.java
src/main/java/org/beep/sbpp/admin/notice/exception/NoticeExceptionHandler.java
src/main/java/org/beep/sbpp/admin/notice/repository/NoticeRepository.java
src/main/java/org/beep/sbpp/admin/notice/service/NoticeService.java
src/main/java/org/beep/sbpp/admin/notice/service/NoticeServiceImpl.java

[🌱feat] 공지사항 백엔드 기능 구현

---

src/main/java/org/beep/sbpp/config/QuerydslConfig.java
src/main/java/org/beep/sbpp/points/PointLogsDesc.java
src/main/java/org/beep/sbpp/points/PointLogsType.java
src/main/java/org/beep/sbpp/points/PointProductType.java
src/main/java/org/beep/sbpp/points/dto/PointLogsDTO.java
src/main/java/org/beep/sbpp/points/dto/PointStoreDTO.java
src/main/java/org/beep/sbpp/points/dto/UserCouponDTO.java
src/main/java/org/beep/sbpp/points/entities/BaseEntity.java
src/main/java/org/beep/sbpp/points/entities/PointEntity.java
src/main/java/org/beep/sbpp/points/entities/PointLogsEntity.java
src/main/java/org/beep/sbpp/points/entities/PointStoreEntity.java
src/main/java/org/beep/sbpp/points/repository/PointStoreRepository.java
src/main/java/org/beep/sbpp/points/service/PointStoreService.java
src/main/java/org/beep/sbpp/points/service/PointStoreServiceImpl.java
src/main/java/org/beep/sbpp/reviews/repository/ReviewRepository.java
src/main/java/org/beep/sbpp/reviews/repository/ReviewSearch.java
src/main/java/org/beep/sbpp/reviews/repository/ReviewSearchImpl.java
src/test/java/org/beep/sbpp/points/PointsRepoTests.java
src/test/java/org/beep/sbpp/points/PointsServiceTests.java

---
- PointStore CRUD 기능 구현
---
- postman 테스트
- 프론트 엔드 연결
---
---
---
---

feat(points): PointStore CRUD 기능 구현

---

src/main/java/org/beep/sbpp/auth/controller/SocalController.java
src/main/java/org/beep/sbpp/auth/dto/GoogleAuthCodeRequestDTO.java
src/main/java/org/beep/sbpp/auth/dto/GoogleTokenRequestDTO.java
src/main/java/org/beep/sbpp/auth/dto/LoginResponseDTO.java
src/main/java/org/beep/sbpp/auth/service/MemberService.java
src/main/java/org/beep/sbpp/auth/service/MemberServiceImpl.java
src/main/java/org/beep/sbpp/config/CustomSecurityConfig.java
src/main/resources/application.yml

[📦 refactor] 구글 로그인 인증 쿠키 저장
---
---
---
JWT로 암호화랑 환경변수 설정
---
- [] 새로운 기능 추가
---
---
---

refactor(auth): 구글 로그인 인증 쿠키 저장

---

src/main/java/org/beep/sbpp/admin/notice/controller/NoticeController.java
src/main/java/org/beep/sbpp/admin/notice/dto/NoticeRequestDTO.java
src/main/java/org/beep/sbpp/admin/notice/dto/NoticeResponseDTO.java
src/main/java/org/beep/sbpp/admin/notice/service/NoticeService.java
src/main/java/org/beep/sbpp/admin/notice/service/NoticeServiceImpl.java
src/main/java/org/beep/sbpp/config/CustomSecurityConfig.java
src/main/java/org/beep/sbpp/config/WebConfig.java
src/test/java/org/beep/sbpp/admin/notice/service/NoticeServiceIntegrationTest.java

[🌱feat] 공지사항 백엔드 기능 구현
---
---
- 다중 이미지 업로드 구현 테스트 및 프론트엔드에서도 확인
- DTO 파일들 제목 수정..
- CustomSecurityConfig의 인가 규칙은 기능 확인을 위해 .permitAll()로 임시 설정(통합 시 해당 파일 무시)
---
---
---
---
---

feat(admin/notice): 공지사항 백엔드 기능 구현

---

.gitignore
src/main/java/org/beep/sbpp/common/BaseEntity2.java
src/main/java/org/beep/sbpp/config/CustomSecurityConfig.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewAddDTO.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewDetailDTO.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewModifyDTO.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewReportDTO.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewSimpleDTO.java
src/main/java/org/beep/sbpp/reviews/entities/ReviewReportEntity.java
src/main/java/org/beep/sbpp/reviews/enums/ReportReason.java
src/main/java/org/beep/sbpp/reviews/repository/ReviewReportRepository.java
src/main/java/org/beep/sbpp/reviews/service/ReviewReportService.java
src/main/java/org/beep/sbpp/reviews/service/ReviewReportServiceImpl.java
src/test/java/org/beep/sbpp/review/ReviewReportServiceTest.java

- 리뷰(Review): User 테이블과 외래키로 연결, 리뷰 이미지 처리
- 리뷰 신고(ReviewReport): 리뷰 신고 기능 구현

[🌱 feat] 리뷰 신고 기능 구현, 유저 테이블과 연결, 이미지 처리

---

src/main/java/org/beep/sbpp/auth/filter/JWTCheckFilter.java
src/main/java/org/beep/sbpp/tags/controller/TagController.java
src/main/java/org/beep/sbpp/tags/dto/TagDTO.java
src/main/java/org/beep/sbpp/tags/dto/TagSelectionDTO.java
src/main/java/org/beep/sbpp/tags/service/TagService.java
src/main/java/org/beep/sbpp/tags/service/TagServiceImpl.java
src/test/java/org/beep/sbpp/users/UserServiceTest.java

[📦 refactor] tag 조회 기능

---

src/main/java/org/beep/sbpp/auth/controller/SocialController.java
src/main/java/org/beep/sbpp/auth/dto/LoginResponseDTO.java
src/main/java/org/beep/sbpp/auth/service/MemberServiceImpl.java
src/main/java/org/beep/sbpp/users/controller/UserController.java
src/main/java/org/beep/sbpp/users/dto/UserSignupRequestDTO.java
src/main/java/org/beep/sbpp/users/entities/UserEntity.java
src/main/java/org/beep/sbpp/users/service/UserServiceImpl.java
src/main/java/org/beep/sbpp/util/JWTUtil.java
src/test/java/org/beep/sbpp/points/PointsServiceTests.java
src/test/java/org/beep/sbpp/tags/TagRepoTests.java

[📦 refactor] 구글 회원가입 시 프로필 처리 추가

---

src/main/java/org/beep/sbpp/products/controller/ProductController.java
src/main/java/org/beep/sbpp/products/dto/ProductDetailDTO.java
src/main/java/org/beep/sbpp/products/dto/ProductListDTO.java
src/main/java/org/beep/sbpp/products/entities/ProductEntity.java
src/main/java/org/beep/sbpp/products/repository/ProductRepository.java
src/main/java/org/beep/sbpp/products/repository/ProductRepositoryCustom.java
src/main/java/org/beep/sbpp/products/repository/ProductRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/products/service/ProductService.java
src/main/java/org/beep/sbpp/products/service/ProductServiceImpl.java

- QueryDSL 사용
- 카테고리/키워드 동시 조건 사용 가능
- 랭킹/상세 정보 페이지에서 별점 및 리뷰 개수 확인할 수 있도록 수정
- 태그 검색 기능은 아직 구현 X

[🌱 feat] 상품 정렬/검색 기능 구현 

---

src/main/java/org/beep/sbpp/products/controller/ProductController.java
src/main/java/org/beep/sbpp/products/dto/ProductDetailDTO.java
src/main/java/org/beep/sbpp/products/entities/ProductEntity.java
src/main/java/org/beep/sbpp/products/entities/ProductLikeEntity.java
src/main/java/org/beep/sbpp/products/repository/ProductLikeRepository.java
src/main/java/org/beep/sbpp/products/service/ProductLikeService.java
src/main/java/org/beep/sbpp/products/service/ProductLikeServiceImpl.java
src/main/java/org/beep/sbpp/products/service/ProductServiceImpl.java

- regDate, modDate를 common/BaseEntity에서 상속받도록 수정

[📦 refactor] BaseEntity 사용

---

src/main/java/org/beep/sbpp/products/repository/ProductRepositoryCustomImpl.java

- DB에 맞게 상품 카테고리 개선(번역 작업 후 추가 수정 예정)

[📦 refactor] 카테고리 개선

---

src/main/java/org/beep/sbpp/products/repository/ProductLikeRepository.java
src/main/java/org/beep/sbpp/users/repository/UserFavoriteRepository.java
src/main/java/org/beep/sbpp/users/service/UserFavoriteService.java
src/main/java/org/beep/sbpp/users/service/UserFavoriteServiceImpl.java

- 필터링 드롭다운 바 제거하여 랭킹 페이지와 유사하게 구현
- 상품 좋아요 수정시간 갱신 안되는 문제 수정
- 찜한 상품 페이지 정렬은 최근 상품 좋아요를 누른 순(수정 시간 최신 순)

[🌱 feat] mypage/favorites 구현

---

src/main/java/org/beep/sbpp/barcode/controller/BarcodeController.java
src/main/java/org/beep/sbpp/barcode/dto/ViewHistoryResponseDTO.java
src/main/java/org/beep/sbpp/barcode/entities/BarcodeHistoryEntity.java
src/main/java/org/beep/sbpp/barcode/repository/BarcodeHistoryRepository.java
src/main/java/org/beep/sbpp/barcode/repository/SaveHistoryRepository.java
src/main/java/org/beep/sbpp/barcode/service/BarcodeService.java
src/main/java/org/beep/sbpp/barcode/service/BarcodeServiceImpl.java
src/main/java/org/beep/sbpp/reviews/controller/ReviewController.java

- 리뷰 작성 시 가장 최근의 해당 상품의 바코드 히스토리 비활성화 (존재한다면)

[🌱 feat] 바코드 히스토리 페이지 구현

---

src/main/java/org/beep/sbpp/Application.java
src/main/java/org/beep/sbpp/users/controller/UserAdminController.java
src/main/java/org/beep/sbpp/users/dto/AdminUsersDetailResDTO.java
src/main/java/org/beep/sbpp/users/dto/AdminUsersListResDTO.java
src/main/java/org/beep/sbpp/users/dto/StatusUpdateDTO.java
src/main/java/org/beep/sbpp/users/entities/UserEntity.java
src/main/java/org/beep/sbpp/users/repository/UserRepository.java
src/main/java/org/beep/sbpp/users/scheduler/UserStatusScheduler.java
src/main/java/org/beep/sbpp/users/service/UserService.java
src/main/java/org/beep/sbpp/users/service/UserServiceImpl.java

- 사용자 상세 DTO, Repository, controller, service
- 사용자 상태 바꾸기 기능, Scheduler 추가

[🌱 feat] 어드민 사용자 상세보기 

---

src/main/java/org/beep/sbpp/config/CustomSecurityConfig.java
src/main/java/org/beep/sbpp/reviews/controller/ReviewController.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewDetailDTO.java
src/main/java/org/beep/sbpp/reviews/entities/ReviewEntity.java
src/main/java/org/beep/sbpp/reviews/service/ReviewReportServiceImpl.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java

- AdminReview, AdminReviewReport api 구현

[🌱 feat] 관리자 리뷰 관리, 관리자 리뷰 신고 관리 구현

---

src/main/java/org/beep/sbpp/auth/controller/SocialController.java
src/main/java/org/beep/sbpp/inquiries/controller/InquiryController.java
src/main/java/org/beep/sbpp/inquiries/dto/DeleteImageRequestDTO.java
src/main/java/org/beep/sbpp/inquiries/dto/InquiryResponseDTO.java
src/main/java/org/beep/sbpp/inquiries/entities/Inquiry.java
src/main/java/org/beep/sbpp/inquiries/service/InquiryService.java
src/main/java/org/beep/sbpp/inquiries/service/InquiryServiceImpl.java

[📦 refactor] 문의 게시판 구체화
---
---
---
---

[📦 refactor] 문의 게시판 구체화

---

build.gradle
src/main/java/org/beep/sbpp/users/controller/UserAdminController.java
src/main/java/org/beep/sbpp/users/dto/AdminUsersListResDTO.java
src/main/java/org/beep/sbpp/users/dto/StatusUpdateDTO.java
src/main/java/org/beep/sbpp/users/entities/UserEntity.java
src/main/java/org/beep/sbpp/users/repository/UserRepository.java
src/main/java/org/beep/sbpp/users/scheduler/UserStatusScheduler.java
src/main/java/org/beep/sbpp/users/service/UserService.java
src/main/java/org/beep/sbpp/users/service/UserServiceImpl.java

[🐛 fix] 자동 상태 변경 기능 수정
---
---
- status 변경 값을 null로 받아오는 문제 해결
- 정지 기간 DB에 반영 안되는 문제 해결
---
---

[🐛 fix] 자동 상태 변경 기능 수정

---

src/main/java/org/beep/sbpp/admin/reviews/controller/AdminReviewController.java
src/main/java/org/beep/sbpp/admin/reviews/repository/AdminReviewReportRepositoryCustom.java
src/main/java/org/beep/sbpp/admin/reviews/repository/AdminReviewReportRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/admin/reviews/repository/AdminReviewRepositoryCustom.java
src/main/java/org/beep/sbpp/admin/reviews/repository/AdminReviewRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/admin/reviews/service/AdminReviewReportService.java
src/main/java/org/beep/sbpp/admin/reviews/service/AdminReviewReportServiceImpl.java
src/main/java/org/beep/sbpp/admin/reviews/service/AdminReviewService.java
src/main/java/org/beep/sbpp/admin/reviews/service/AdminReviewServiceImpl.java
src/main/java/org/beep/sbpp/products/entities/ProductEntity.java
src/main/java/org/beep/sbpp/products/entities/ProductTagEntity.java
src/main/java/org/beep/sbpp/products/repository/ProductTagRepository.java
src/main/java/org/beep/sbpp/reviews/repository/ReviewTagRepository.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java

[🌱 feat] 상품 대표 태그 테이블 추가 및 로직 구현
---
---
- ProductTagEntity - 리뷰 추가시 상품에 달린 태그 개수 갱신
- ProductEntity - 리뷰 추가시 상품 대표 태그 mainTag 갱신
---
---

[🌱 feat] 상품 대표 태그 테이블 추가 및 로직 구현

---

src/main/java/org/beep/sbpp/admin/auth/controller/AdminAuthController.java
src/main/java/org/beep/sbpp/admin/auth/entities/AdminEntity.java
src/main/java/org/beep/sbpp/admin/auth/repository/AdminAuthRepository.java
src/main/java/org/beep/sbpp/admin/auth/service/AdminAuthService.java
src/main/java/org/beep/sbpp/admin/auth/service/AdminAuthServiceImpl.java
src/main/java/org/beep/sbpp/auth/filter/JWTCheckFilter.java
src/main/java/org/beep/sbpp/auth/service/MemberServiceImpl.java
src/main/java/org/beep/sbpp/config/CustomSecurityConfig.java

[🌱 feat] 어드민 로그인 구현
---
---
- 어드민 로그인 구현
---
---

[🌱 feat] 어드민 로그인 구현

---

src/main/java/org/beep/sbpp/admin/users/controller/UserAdminController.java
src/main/java/org/beep/sbpp/admin/users/dto/AdminUsersDetailResDTO.java
src/main/java/org/beep/sbpp/admin/users/dto/AdminUsersListResDTO.java
src/main/java/org/beep/sbpp/admin/users/dto/StatusUpdateDTO.java
src/main/java/org/beep/sbpp/admin/users/repository/AdminUserRepository.java
src/main/java/org/beep/sbpp/admin/users/repository/AdminUserRepositoryCustom.java
src/main/java/org/beep/sbpp/admin/users/repository/AdminUserRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/admin/users/service/AdminUserService.java
src/main/java/org/beep/sbpp/admin/users/service/AdminUserServiceImpl.java
src/main/java/org/beep/sbpp/users/service/UserService.java
src/main/java/org/beep/sbpp/users/service/UserServiceImpl.java

[🌱 feat] 어드민 사용자 검색기능 추가
---
---
---
---

[🌱 feat] 어드민 사용자 검색기능 추가

---

src/main/java/org/beep/sbpp/map/controller/MapController.java
src/main/java/org/beep/sbpp/points/controller/PointController.java
src/main/resources/application.yml

[🌱 feat] ORS API 길찾기 경로 호출
---
---
- 도보 길찾기 경로 호출
- mapController 작성
---
---

[🌱 feat] ORS API 길찾기 경로 호출

---

src/main/java/org/beep/sbpp/products/controller/ProductController.java
src/main/java/org/beep/sbpp/products/repository/ProductTagUserRepository.java
src/main/java/org/beep/sbpp/products/repository/ProductTagUserRepositoryImpl.java
src/main/java/org/beep/sbpp/products/service/ProductService.java
src/main/java/org/beep/sbpp/products/service/ProductServiceImpl.java

[🌱 feat] 상품 추천 페이지 구현
---
---
- 상품 태그에 대해 사용자 태그로 검색하여 목록에 보여주는 기능 구현
---
---

[🌱 feat] 상품 추천 페이지 구현

---

src/main/java/org/beep/sbpp/admin/inquiries/controller/AdminInquiryController.java
src/main/java/org/beep/sbpp/admin/inquiries/service/AdminInquiryService.java
src/main/java/org/beep/sbpp/admin/inquiries/service/AdminInquiryServiceImpl.java
src/main/java/org/beep/sbpp/inquiries/dto/InquiryResponseDTO.java
src/main/java/org/beep/sbpp/inquiries/repository/InquiryRepository.java
src/main/java/org/beep/sbpp/inquiries/service/InquiryService.java
src/main/java/org/beep/sbpp/inquiries/service/InquiryServiceImpl.java
src/main/java/org/beep/sbpp/users/repository/UserProfileRepository.java

[🌱 feat] 어드민페이지 문의사항 기능 구현
---
- 문의사항 답변 미완
---
---
---

[🌱 feat] 어드민페이지 문의사항 기능 구현

---

src/main/java/org/beep/sbpp/admin/reviews/dto/AdminReviewDetailDTO.java
src/main/java/org/beep/sbpp/admin/reviews/service/AdminReviewServiceImpl.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java

[📦 refactor] AdminReviewDetailDTO 이메일 추가, 리뷰 커멘트 유효성 판단
---
---
---
---

[📦 refactor] AdminReviewDetailDTO 이메일 추가, 리뷰 커멘트 유효성 판단

---

src/main/java/org/beep/sbpp/users/controller/UserController.java
src/main/java/org/beep/sbpp/users/dto/UserStatusUpdateRequestDTO.java
src/main/java/org/beep/sbpp/users/repository/UserProfileRepository.java
src/main/java/org/beep/sbpp/users/repository/UserRepository.java
src/main/java/org/beep/sbpp/users/service/UserService.java
src/main/java/org/beep/sbpp/users/service/UserServiceImpl.java

[🌱 feat] 계정 삭제 기능 추가
---
- 이메일 중복 확인 기능 추가
- 닉네임 중복 확인 기능 추가
- 계정 삭제 기능 추가
---
---
---

[🌱 feat] 계정 삭제 기능 추가

---

src/main/java/org/beep/sbpp/admin/points/controller/AdminPointController.java
src/main/java/org/beep/sbpp/admin/points/dto/PointStoreAddDTO.java
src/main/java/org/beep/sbpp/admin/points/dto/PointStoreDTO.java
src/main/java/org/beep/sbpp/admin/points/dto/PointStoreListDTO.java
src/main/java/org/beep/sbpp/admin/points/repository/AdminPointRepository.java
src/main/java/org/beep/sbpp/admin/points/repository/AdminPointRepositoryCustom.java
src/main/java/org/beep/sbpp/admin/points/repository/AdminPointRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/admin/points/service/AdminPointService.java
src/main/java/org/beep/sbpp/admin/points/service/AdminPointServiceImpl.java
src/main/java/org/beep/sbpp/config/WebConfig.java
src/main/java/org/beep/sbpp/points/controller/PointController.java
src/main/java/org/beep/sbpp/points/dto/UserCouponDTO.java
src/main/java/org/beep/sbpp/points/entities/PointStoreEntity.java
src/main/java/org/beep/sbpp/points/entities/UserCouponEntity.java
src/main/java/org/beep/sbpp/points/enums/CouponStatus.java
src/main/java/org/beep/sbpp/points/enums/PointProductType.java
src/main/java/org/beep/sbpp/points/repository/PointRepository.java
src/main/java/org/beep/sbpp/points/repository/UserCouponRepository.java
src/main/java/org/beep/sbpp/points/service/PointService.java
src/main/java/org/beep/sbpp/points/service/PointServiceImpl.java
src/main/java/org/beep/sbpp/points/service/UserCouponService.java
src/main/java/org/beep/sbpp/points/service/UserCouponServiceImpl.java
src/main/java/org/beep/sbpp/util/FileUploadUtil.java
src/main/resources/application.yml
src/test/java/org/beep/sbpp/points/PointsRepoTests.java
src/test/java/org/beep/sbpp/points/PointsServiceTests.java
src/test/java/org/beep/sbpp/users/UserRepoTests.java

[🌱 feat] 어드민 검색 기능 개발 
---
- 어드민 포인트 상품 검색 기능 개발
- 사진업로드, 경로 NGINX로 전환
---
---
---

[🌱 feat] 어드민 검색 기능 개발 

---

src/main/java/org/beep/sbpp/points/controller/PointController.java
src/main/java/org/beep/sbpp/points/repository/UserCouponRepository.java
src/main/java/org/beep/sbpp/points/service/PointService.java
src/main/java/org/beep/sbpp/points/service/PointServiceImpl.java
src/main/java/org/beep/sbpp/points/service/UserCouponService.java
src/main/java/org/beep/sbpp/points/service/UserCouponServiceImpl.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java

[🌱 feat] 쿠폰 개수 api 생성, 연결 
---
- 쿠폰 개수 api 생성
---
---
---

[🌱 feat] 쿠폰 개수 api 생성, 연결 

---

src/main/java/org/beep/sbpp/common/PageResponse.java
src/main/java/org/beep/sbpp/products/controller/ProductController.java
src/main/java/org/beep/sbpp/products/dto/ProductListDTO.java
src/main/java/org/beep/sbpp/products/repository/ProductRepositoryCustom.java
src/main/java/org/beep/sbpp/products/repository/ProductRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/products/repository/ProductTagUserRepository.java
src/main/java/org/beep/sbpp/products/repository/ProductTagUserRepositoryImpl.java
src/main/java/org/beep/sbpp/products/service/ProductService.java
src/main/java/org/beep/sbpp/products/service/ProductServiceImpl.java
src/main/java/org/beep/sbpp/users/controller/UserController.java
src/main/java/org/beep/sbpp/users/repository/UserFavoriteRepository.java
src/main/java/org/beep/sbpp/users/repository/UserFavoriteRepositoryCustom.java
src/main/java/org/beep/sbpp/users/repository/UserFavoriteRepositoryImpl.java
src/main/java/org/beep/sbpp/users/service/UserFavoriteService.java
src/main/java/org/beep/sbpp/users/service/UserFavoriteServiceImpl.java

[📦 refactor] 상품 목록 페이지 OFFSET -> CURSOR 방식 전환
---
- 무한스크롤 사용에 따른 페이징 방식 변경
- 추후 AI검색/ES 도입에도 유리
---
---
---

[📦 refactor] 상품 목록 페이지 OFFSET -> CURSOR 방식 전환

---

src/main/java/org/beep/sbpp/admin/notice/controller/AdminNoticeController.java
src/main/java/org/beep/sbpp/admin/notice/repository/AdminNoticeRepository.java
src/main/java/org/beep/sbpp/admin/notice/service/AdminNoticeService.java
src/main/java/org/beep/sbpp/admin/notice/service/AdminNoticeServiceImpl.java

제목
---
- 검색 기능 구현
- Pagination 사용하도록 수정
- axiosInstance -> axiosInstanceAdmin 적용
---
---
---

[📦 refactor] 관리자 공지사항 페이지 개선

---

src/main/java/org/beep/sbpp/barcode/controller/BarcodeController.java
src/main/java/org/beep/sbpp/barcode/dto/ViewHistoryResponseDTO.java
src/main/java/org/beep/sbpp/barcode/entities/BarcodeHistoryEntity.java
src/main/java/org/beep/sbpp/barcode/repository/BarcodeHistoryRepository.java
src/main/java/org/beep/sbpp/barcode/service/BarcodeService.java
src/main/java/org/beep/sbpp/barcode/service/BarcodeServiceImpl.java

[📦 refactor] 바코드 히스토리 UI 개선
---
---
---
---

[📦 refactor] 바코드 히스토리 UI 개선

---

build.gradle
src/main/java/org/beep/sbpp/config/GoogleNlpConfig.java
src/main/java/org/beep/sbpp/reviews/controller/ReviewSummaryController.java
src/main/java/org/beep/sbpp/reviews/entities/ReviewSentimentEntity.java
src/main/java/org/beep/sbpp/reviews/enums/SentimentType.java
src/main/java/org/beep/sbpp/reviews/repository/ReviewSentimentRepository.java
src/main/java/org/beep/sbpp/reviews/service/ReviewSentimentAnalyzer.java
src/main/java/org/beep/sbpp/reviews/service/ReviewSentimentService.java
src/main/java/org/beep/sbpp/reviews/service/ReviewSentimentServiceImpl.java
src/main/java/org/beep/sbpp/util/scheduler/ReviewSentimentScheduler.java
src/main/java/org/beep/sbpp/util/scheduler/UserStatusScheduler.java

[🌱 feat] 리뷰 감정분석 기능 추가
---
- 한시간마다 실행됨
- 환경변수 설정 필요
---
---
---

[🌱 feat] 리뷰 감정분석 기능 추가

---

src/main/java/org/beep/sbpp/config/GoogleNlpConfig.java
src/main/java/org/beep/sbpp/reviews/service/ReviewSentimentAnalyzer.java
src/main/java/org/beep/sbpp/util/scheduler/ReviewSentimentScheduler.java

[🐛 fix] 주석처리 올리기
---
---
---
---

[🐛 fix] 주석처리 올리기

---

src/main/java/org/beep/sbpp/admin/products/controller/AdminProductController.java
src/main/java/org/beep/sbpp/products/dto/ProductListDTO.java
src/main/java/org/beep/sbpp/products/entities/ProductEntity.java

제목
---
- 이미지 webp로 변환
- 상품 목록 조회 시 썸네일 적용
---
- [] 새로운 기능 추가
---
---

[📦 refactor] 상품 목록 페이지 개선

---

src/main/java/org/beep/sbpp/reviews/controller/ReviewTranslateController.java
src/main/java/org/beep/sbpp/reviews/dto/ReviewSimpleDTO.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java
src/main/java/org/beep/sbpp/reviews/service/ReviewTranslateService.java
src/main/java/org/beep/sbpp/reviews/service/ReviewTranslateServiceImpl.java

[🌱 feat] 리뷰 번역 기능 구현 
---
- gpt-3.5-turbo api를 호출하여 사용자 국적에 맞게 리뷰를 번역
---
---
---

[🌱 feat] 리뷰 번역 기능 구현 

---

src/main/java/org/beep/sbpp/admin/products/dto/ProductRequestDTO.java
src/main/java/org/beep/sbpp/admin/products/service/AdminProductImageStorageService.java
src/main/java/org/beep/sbpp/admin/products/service/AdminProductImageStorageServiceImpl.java
src/main/java/org/beep/sbpp/admin/products/service/AdminProductService.java
src/main/java/org/beep/sbpp/admin/products/service/AdminProductServiceImpl.java

[📦 refactor] 상품 업로드 로직 수정
---
- 썸네일 변환 기능 추가
- webp 변환은 아직 안됨
---
---
---

[📦 refactor] 상품 업로드 로직 수정

---

build.gradle
src/main/java/org/beep/sbpp/Application.java
src/main/java/org/beep/sbpp/config/EnvVarPostProcessor.java
src/main/java/org/beep/sbpp/products/controller/ProductSearchController.java
src/main/java/org/beep/sbpp/products/document/ProductSearchDocument.java
src/main/java/org/beep/sbpp/products/repository/ProductSearchRepository.java
src/main/java/org/beep/sbpp/products/service/ProductSearchService.java
src/main/resources/META-INF/spring.factories
src/main/resources/application.yml

[🌱 feat] ElasticSearch 연동 및 테스트
---
- spring으로 ES 작동 확인(Talend 사용)
- spring.factories : .env의 로딩 시점이 Spring Bean 초기화보다 늦어 @Value가 null로 주입되는 문제 해결을 위한 파일
---
---
---

[🌱 feat] ElasticSearch 연동 및 테스트

---

src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java

- AdminDashboard 문의사항, 통계 그래프, 이번달 수치 api
제목
---
---
---
---

[🐛 fix] 이미지 경로 오타 수정

---

build.gradle
settings.gradle
src/main/java/org/beep/sbpp/chatbot/controller/ChatbotController.java
src/main/java/org/beep/sbpp/chatbot/dto/ChatRequestDTO.java
src/main/java/org/beep/sbpp/chatbot/dto/FaqVectorDTO.java
src/main/java/org/beep/sbpp/chatbot/entities/ChatbotFaqEntity.java
src/main/java/org/beep/sbpp/chatbot/repository/ChatbotFaqRepository.java
src/main/java/org/beep/sbpp/chatbot/service/ChatbotEmbeddingService.java
src/main/java/org/beep/sbpp/chatbot/service/ChatbotEmbeddingServiceImpl.java
src/main/java/org/beep/sbpp/chatbot/service/ChatbotService.java
src/main/java/org/beep/sbpp/chatbot/service/ChatbotServiceImpl.java
src/main/resources/schema.sql
src/test/java/org/beep/sbpp/chatbot/ChatbotServiceTests.java

[🌱 feat] 서비스 관련 질문 FAQ 벡터화
---
- FAQ 관련 백터화, 유사도검색 로직 추가
---
---
---

[🌱 feat] 서비스 관련 질문 FAQ 벡터화

---

src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java
src/main/java/org/beep/sbpp/summary/repository/ReviewSentimentRepository.java

[🌱 feat] 리뷰 삭제시 리뷰 감정 테이블도 함께 삭제

---

src/main/java/org/beep/sbpp/points/controller/PointController.java
src/main/java/org/beep/sbpp/points/repository/PointRepository.java
src/main/java/org/beep/sbpp/points/repository/UserCouponRepository.java
src/main/java/org/beep/sbpp/points/service/PointService.java
src/main/java/org/beep/sbpp/points/service/PointServiceImpl.java

[📦 refactor] 포인트양 조회 api 추가
---
---
---
---

[📦 refactor] 포인트양 조회 api 추가

---

build.gradle
src/main/java/org/beep/sbpp/chatbot/service/ChatbotEmbeddingServiceImpl.java
src/main/java/org/beep/sbpp/chatbot/service/ChatbotServiceImpl.java
src/main/resources/schema.sql

제목
[🐛 fix] 챗봇 언어감지, 에러 수정
---
- 프롬프트에 언어 감지 추가
- 요청시 history 제거해서 에러 개선
---
---
---

[🐛 fix] 챗봇 언어감지, 에러 수정

---

docker-compose.yml

[🐛 fix] 도커 컴포즈 파일 수정
---
---
---
---

[🐛 fix] 도커 컴포즈 파일 수정

---

src/main/java/org/beep/sbpp/config/EnvVarPostProcessor.java
src/main/java/org/beep/sbpp/products/entities/ProductBaseEntity.java
src/main/java/org/beep/sbpp/products/entities/ProductEnEntity.java
src/main/java/org/beep/sbpp/products/entities/ProductJaEntity.java
src/main/java/org/beep/sbpp/products/entities/ProductKoEntity.java
src/main/java/org/beep/sbpp/products/service/ProductServiceImpl.java
src/main/java/org/beep/sbpp/search/config/ElasticsearchConfig.java
src/main/java/org/beep/sbpp/search/service/ProductSearchIndexer.java
src/main/java/org/beep/sbpp/search/service/ProductSearchServiceImpl.java
src/main/java/org/beep/sbpp/util/scheduler/ProductSearchScheduler.java
src/main/resources/META-INF/spring.factories
src/main/resources/application.yml

[🐛 fix] 인덱싱 N+1문제 해결
---
- ES 인덱싱 시 발생하는 N+1문제 해결
- ProductServiceImpl, Entity에서 잠재적 N+1 문제 가능성 때문에 BatchSize 적용
---
---
---

[🐛 fix] 인덱싱 N+1문제 해결

---

src/main/java/org/beep/sbpp/admin/products/dto/ProductRequestDTO.java
src/main/java/org/beep/sbpp/admin/products/repository/AdminProductRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/admin/products/service/AdminProductServiceImpl.java
src/main/java/org/beep/sbpp/admin/reviews/repository/AdminReviewRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/admin/reviews/service/AdminReviewServiceImpl.java
src/main/java/org/beep/sbpp/barcode/service/BarcodeServiceImpl.java
src/main/java/org/beep/sbpp/chatbot/service/ChatbotEmbeddingServiceImpl.java
src/main/java/org/beep/sbpp/products/repository/ProductRepositoryCustomImpl.java
src/main/java/org/beep/sbpp/products/service/ProductServiceImpl.java
src/main/java/org/beep/sbpp/push/service/PushScheduleServiceImpl.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java
src/main/java/org/beep/sbpp/users/service/UserFavoriteServiceImpl.java

[🐛 fix] 회원가입 후 토큰 오류 발생 문제 해결
---
- ko-KR이 언어로 입력되어 오류 발생하는 문제 해결
---
---
---

[🐛 fix] 회원가입 후 토큰 오류 발생 문제 해결

---

src/main/java/org/beep/sbpp/config/CustomSecurityConfig.java
src/main/java/org/beep/sbpp/reviews/service/ReviewServiceImpl.java
src/main/java/org/beep/sbpp/users/service/UserServiceImpl.java
src/main/resources/application.yml

[📦 refactor] 사진 경로 수정
---
- 이미지 저장 경로 수정
---
- [] 새로운 기능 추가
---
---

[📦 refactor] 사진 경로 수정

---

src/main/java/org/beep/sbpp/search/service/ProductSearchServiceImpl.java
src/main/resources/elasticsearch/products-mappings-en.json
src/main/resources/elasticsearch/products-mappings-ja.json
src/main/resources/elasticsearch/products-mappings-ko.json
src/main/resources/elasticsearch/products-settings-en.json
src/main/resources/elasticsearch/products-settings-ja.json
src/main/resources/elasticsearch/products-settings-ko.json

[🐛 fix] ES 인덱싱 적용 문제 해결
---
mappings, settings 수정
---
- [] 새로운 기능 추가
---
---

[🐛 fix] ES 인덱싱 적용 문제 해결
